theme: jekyll-theme-slate
title: Venkata Krishnan Anantha Raman
description: Actively seeking Internships in Summer:2018
author: Venkata Krishnan Anantha Raman
##Social links
github: https://github.com/venkatsvpr 
