theme: jekyll-theme-slate
title: Venkata Krishnan Anantha Raman
tagline: Looking out for Summer Internships-2018
author: Venkata Krishnan Anantha Raman
##Social links
github: https://github.com/venkatsvpr 
