theme: jekyll-theme-slate
title: Venkata Krishnan Anantha Raman
description: Software Engineer actively seeking Summer Internships starting May 2018.
author: Venkata Krishnan Anantha Raman
##Social links
github: https://github.com/venkatsvpr 
